### ISSUE TITLE
Failed buidling the test enclave

### ISSUE THREAD

**Issue by sewelol** [01org/intel-sgx-ssl#3]
I am trying to compile on Ubuntu 16.04 using OpenSSL 1.1.0f and I get this error message when running the build script:
```
../../package/lib64/release//libsgx_tsgxssl_crypto.a(async.o): In function `async_fibre_swapcontext.constprop.2':
async.c:(.text+0x1b): undefined reference to `_setjmp'
async.c:(.text+0x51): undefined reference to `_longjmp'
collect2: error: ld returned 1 exit status
sgx_t.mk:150: recipe for target 'TestEnclave.so' failed
```

**Comment by sewelol** [comment]
Seems the _setjump and _longjmp was changed to setjmp and longjmp in the lastest commit in the SDK.
[Before: Linux 1.9 Open Source Gold release](https://github.com/01org/linux-sgx/blame/199911ebaf60d068e4641331a06e71462ba8d324/common/inc/tlibc/setjmp.h)

I will try using the older SDK.

**Comment by sewelol** [comment]
Seems the _setjump and _longjmp was changed to setjmp and longjmp in the lastest commit in the SDK.
[Before: Linux 1.9 Open Source Gold release](https://github.com/01org/linux-sgx/blame/199911ebaf60d068e4641331a06e71462ba8d324/common/inc/tlibc/setjmp.h)

I will try using the older SDK.

**Comment by zhhailon** [comment]
Or add
```c
#define _longjmp longjmp
#define _setjmp setjmp
```
in  `openssl_source/bypass_to_sgxssl.h`.

**Comment by akryeem-INTC** [comment]
As you mentioned this issue was caused by SDK 1.9 API name changes.
This issue was fixed.
